"""initial schema: all Phase 0 tables

Initial revision builds from the models so schema and code start identical. Every later change
must be a normal autogenerated revision (alembic revision --autogenerate -m "...").

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-22
"""
from alembic import op

import app.models  # noqa: F401
from app.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
