"""initial schema: pgvector + all Phase 0 tables

Initial revision builds from the models so schema and code start identical. Every later change
must be a normal autogenerated revision (alembic revision --autogenerate -m "...").

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-22
"""
from alembic import op

import app.models  # noqa: F401
from app.config import settings
from app.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    # HNSW index for cosine search over chunk embeddings (pgvector supports HNSW up to 2000 dims).
    if settings.embedding_dim <= 2000:
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_chunks_embedding_hnsw ON chunks "
            "USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
