// Generated by scripts/make_demo_vo.py: narration clip lengths in seconds. Do not edit by hand.
export const DEMO_VO_SECONDS = {"warp": 3.61, "sync": 2.25, "map": 5.17, "kit": 2.95, "outro": 2.8} as const;
