// Generated by scripts/make_demo_vo.py: narration clip lengths in seconds. Do not edit by hand.
export const DEMO_VO_SECONDS = {"warp": 3.92, "paste": 6.95, "orbit": 6.61, "research": 3.74, "audio": 2.67, "launchkit": 3.32, "launchpad": 4.05, "outro": 2.48} as const;
