// Generated by make_launch_music.py from public/launch-vo/durations.json. Do not edit by hand.
// 120 bpm; every scene starts on a bar line so cuts land on the beat.
export const LAUNCH_BPM = 120;
export const LAUNCH_SECONDS = 84.0;
export const LAUNCH_SCENES = [
  { id: "intro", start: 0.0, len: 8.0, vo: 1.0, voLen: 5.78 },
  { id: "launch", start: 8.0, len: 4.0, vo: 0.35, voLen: 3.03 },
  { id: "sources", start: 12.0, len: 8.0, vo: 0.35, voLen: 6.14 },
  { id: "research", start: 20.0, len: 6.0, vo: 0.35, voLen: 4.16 },
  { id: "map", start: 26.0, len: 8.0, vo: 0.35, voLen: 6.12 },
  { id: "voice", start: 34.0, len: 6.0, vo: 0.35, voLen: 4.57 },
  { id: "audio", start: 40.0, len: 6.0, vo: 0.35, voLen: 3.69 },
  { id: "video", start: 46.0, len: 6.0, vo: 0.35, voLen: 4.44 },
  { id: "launchkit", start: 52.0, len: 6.0, vo: 0.35, voLen: 4.7 },
  { id: "launchpad", start: 58.0, len: 6.0, vo: 0.35, voLen: 3.32 },
  { id: "resurface", start: 64.0, len: 6.0, vo: 0.35, voLen: 4.23 },
  { id: "montage", start: 70.0, len: 4.0, vo: null, voLen: null },
  { id: "outro", start: 74.0, len: 10.0, vo: 1.2, voLen: 5.17 },
] as const;
export type LaunchSceneId = (typeof LAUNCH_SCENES)[number]["id"];
