// Generated by make_launch_music.py from public/launch-vo/durations.json. Do not edit by hand.
// 120 bpm; every scene starts on a bar line so cuts land on the beat.
export const LAUNCH_BPM = 120;
export const LAUNCH_SECONDS = 92.0;
export const LAUNCH_SCENES = [
  { id: "intro", start: 0.0, len: 8.0, vo: 1.0, voLen: 5.36 },
  { id: "launch", start: 8.0, len: 4.0, vo: 0.35, voLen: 2.85 },
  { id: "sources", start: 12.0, len: 10.0, vo: 0.35, voLen: 8.0 },
  { id: "research", start: 22.0, len: 6.0, vo: 0.35, voLen: 4.94 },
  { id: "map", start: 28.0, len: 8.0, vo: 0.35, voLen: 5.96 },
  { id: "voice", start: 36.0, len: 6.0, vo: 0.35, voLen: 4.52 },
  { id: "audio", start: 42.0, len: 6.0, vo: 0.35, voLen: 3.45 },
  { id: "video", start: 48.0, len: 8.0, vo: 0.35, voLen: 6.61 },
  { id: "launchkit", start: 56.0, len: 8.0, vo: 0.35, voLen: 6.38 },
  { id: "launchpad", start: 64.0, len: 8.0, vo: 0.35, voLen: 5.65 },
  { id: "resurface", start: 72.0, len: 6.0, vo: 0.35, voLen: 3.82 },
  { id: "montage", start: 78.0, len: 4.0, vo: null, voLen: null },
  { id: "outro", start: 82.0, len: 10.0, vo: 1.2, voLen: 5.07 },
] as const;
export type LaunchSceneId = (typeof LAUNCH_SCENES)[number]["id"];
