// Generated by make_launch_music.py from public/launch-vo/durations.json. Do not edit by hand.
// 120 bpm; every scene starts on a bar line so cuts land on the beat.
export const LAUNCH_BPM = 120;
export const LAUNCH_SECONDS = 82.0;
export const LAUNCH_SCENES = [
  { id: "intro", start: 0.0, len: 8.0, vo: 1.0, voLen: 5.83 },
  { id: "launch", start: 8.0, len: 4.0, vo: 0.35, voLen: 2.9 },
  { id: "sources", start: 12.0, len: 8.0, vo: 0.35, voLen: 6.38 },
  { id: "research", start: 20.0, len: 6.0, vo: 0.35, voLen: 4.16 },
  { id: "map", start: 26.0, len: 6.0, vo: 0.35, voLen: 4.47 },
  { id: "voice", start: 32.0, len: 6.0, vo: 0.35, voLen: 3.56 },
  { id: "audio", start: 38.0, len: 4.0, vo: 0.35, voLen: 3.19 },
  { id: "video", start: 42.0, len: 8.0, vo: 0.35, voLen: 5.88 },
  { id: "launchkit", start: 50.0, len: 6.0, vo: 0.35, voLen: 3.69 },
  { id: "launchpad", start: 56.0, len: 6.0, vo: 0.35, voLen: 4.94 },
  { id: "resurface", start: 62.0, len: 6.0, vo: 0.35, voLen: 4.44 },
  { id: "montage", start: 68.0, len: 4.0, vo: null, voLen: null },
  { id: "outro", start: 72.0, len: 10.0, vo: 1.2, voLen: 6.3 },
] as const;
export type LaunchSceneId = (typeof LAUNCH_SCENES)[number]["id"];
